Feature/fastapi chat history
karya-inc/natural-language-query pull request #14
Opened 2024-10-22 05:30 UTC by MalayJoshi-Karya

2024-10-26 08:01 UTC, Mirza-Aasim approved these changes
LGTM!

2024-10-28 02:07 UTC, SoumyaRanjanPatnaik requested changes

2024-10-28 08:44 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/server.py
> +    allow_origins=["*"],  # Allows all origins
Done

2024-10-28 08:53 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/server.py
> +        body = await request.json()
Done

2024-10-28 08:53 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/server.py
> +        body = await request.json()
Done

2024-10-28 10:16 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/chat_history.py
> +def get_chat_history(session_id: str) -> Generator[str, None, None]:
Done

2024-10-28 10:27 UTC, SoumyaRanjanPatnaik approved these changes
LGTM

2024-10-28 10:27 UTC, merged