feat: add chat integration
karya-inc/natural-language-query pull request #16
Opened 2024-10-25 11:06 UTC by ShaikMoAbdullah

- [x] Added chat integration
- [ ] Fixed issues with respect to CORS error by allowing all origins from the backend

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik requested changes

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik commented on frontend/src/screens/Chat.tsx
> +        const response = await fetch("http://127.0.0.1:8000/chat", {
Probably a good idea to keep the urls in a .env file. 

Link for reference: https://vite.dev/guide/env-and-mode#env-files

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/server-sse.py
>          logger.info(f"Started streaming SQL responses for query: {query}")
Why do we need both GET and POST? I guess just using POST would do. Also, we don't need to manually extract data from the request body. FastAPI should do this automatically for us. (reference: https://fastapi.tiangolo.com/tutorial/body/)

Can we also bring back the comments?😅

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik commented on frontend/src/screens/Chat.tsx
> +  const botGreeting = useMemo(
Can be a seperate component I guess?

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik commented on frontend/src/screens/Chat.tsx
> +        const response = await fetch("http://127.0.0.1:8000/chat", {
Might be a good idea to move the API stuff to another function (outside this component). Would clean up the component a little bit. Your call though.

2024-10-27 17:23 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/server-sse.py
> +
Might be a good idea to do get the frontend URL from the .env file
```suggestion
from dotenv import load_dotenv
load_dotenv()

# Configure CORS
allowed_origin = os.environ.get("CORS_ORIGINS", "").split(" ")
app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origin,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```

Inside the `.env` file:
```bash
# Frontend URL
CORS_ORIGINS=http://localhost:3000 
```

2024-10-28 08:30 UTC, ShaikMoAbdullah commented on backend/fastapi-sse/server-sse.py
>          logger.info(f"Started streaming SQL responses for query: {query}")
`Also, we don't need to manually extract data from the request body. FastAPI should do this automatically for us.`

@MalayJoshi-Karya Please make this change

2024-10-28 08:34 UTC, ShaikMoAbdullah commented on backend/fastapi-sse/server-sse.py
>          logger.info(f"Started streaming SQL responses for query: {query}")
@SoumyaRanjanPatnaik Had a very little idea about this. Much of it was done with the help of ChatGPT :smile:

2024-10-28 08:37 UTC, ShaikMoAbdullah commented on frontend/src/screens/Chat.tsx
> +        const response = await fetch("http://127.0.0.1:8000/chat", {
Done

2024-10-28 08:56 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/server-sse.py
>          logger.info(f"Started streaming SQL responses for query: {query}")
@ShaikMoAbdullah the code which you got from Chatgpt has been already fixed by me in the following repo: #14 , you can resolve this conversation.

2024-10-28 08:56 UTC, MalayJoshi-Karya commented on backend/fastapi-sse/server-sse.py
> +
@ShaikMoAbdullah the code which you got from Chatgpt has been already fixed by me in the following repo: #14 , you can resolve this conversation as well.

2024-10-28 12:43 UTC, ShaikMoAbdullah commented
@MalayJoshi-Karya Please look into these merge conflicts

2024-10-28 13:08 UTC, ShaikMoAbdullah commented
Resolved all the merge conflicts

2024-10-29 06:31 UTC, SoumyaRanjanPatnaik approved these changes
LGTM

2024-10-29 08:28 UTC, merged