Code Cleanup
karya-inc/natural-language-query pull request #23
Opened 2024-11-01 11:10 UTC by Mirza-Aasim

- [x] Moved Logger function to utils 
- [x] Moved gemini call to utils function
- [x] Alembic database migration setup
- [ ] Controllers for routes created
- [ ] Updated Routes
- [ ] Dependency injection for user validation

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik requested changes

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/alembic/versions/d876807d293b_initial_migration.py
This file needs formatting. Can you use pylint or something similar to do this (there's probably a vscode extension for this).

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/server-sse.py
> +    print("type", chat_request.type)
Either use logger or remove the prints.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/server.py
> +        response = chat_history(user_id: str)
Invalid function call.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/server-sse.py
We can delete this file right?

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/utils/gemini_service.py
> +def sql_generator(user_query):
Probably need to invoke the query executor code written by edmund here.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/alembic/env.py
> +    run_migrations_online()
What is the difference between offline migrations and online migrations?

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/logger.py
We can delete this right?

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/db/db_queries.py
> +        ai_response=ai_response,
Is `ai_response` the sql query generated by ai or the response after running the query? We probably need to store both.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/db/db_queries.py
This file also requires formatting.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/db/models.py
Can you add type annotations for all the models? Would be useful for auto-completion and type checking.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/server.py
> +async def stream_chat_history(session_id: str) -> StreamingResponse:
Should not be `StreamingResponse`. Doesn't make sense to stream chat history.

2024-11-03 16:44 UTC, SoumyaRanjanPatnaik commented on backend/db/models.py
Also I think this is the older depricated syntax. The documentation suggests using `mapped_column` with type annotations.

2024-11-04 05:54 UTC, Mirza-Aasim commented on backend/alembic/versions/d876807d293b_initial_migration.py
this is autogenerated file, formatting could be different for different user's so I kept it same

2024-11-04 05:54 UTC, Mirza-Aasim commented on backend/fastapi-sse/server-sse.py
> +    print("type", chat_request.type)
This whole file will be removed soon!

2024-11-04 05:55 UTC, Mirza-Aasim commented on backend/server.py
> +        response = chat_history(user_id: str)
Yes because waiting for controller to be finished, i'll update this function

2024-11-04 05:55 UTC, Mirza-Aasim commented on backend/fastapi-sse/server-sse.py
Yes!

2024-11-04 05:56 UTC, Mirza-Aasim commented on backend/utils/gemini_service.py
> +def sql_generator(user_query):
This is utility function for our checks, since we dont have openai keys, but in controller this function will be replaced by Edmund's call to openai

2024-11-04 05:56 UTC, Mirza-Aasim commented on backend/fastapi-sse/logger.py
Yes!

2024-11-04 05:59 UTC, Mirza-Aasim commented on backend/alembic/env.py
> +    run_migrations_online()
Online Mode - Alembic directly connects to the database, the migrations run in real-time, executing SQL statements directly against the target database.
Offline Mode -  Instead of executing SQL statements directly, Alembic generates SQL statements as a script. The generated SQL can then be applied to the database later, possibly on another machine or at a scheduled time.

Read more about this - 
https://alembic.sqlalchemy.org/en/latest/tutorial.html

2024-11-04 06:02 UTC, Mirza-Aasim commented on backend/db/db_queries.py
What formatting do you guys use? i use black

2024-11-04 06:03 UTC, Mirza-Aasim commented on backend/db/models.py
Sure i'll look into it! Thanks!

2024-11-04 06:03 UTC, Mirza-Aasim commented on backend/server.py
> +async def stream_chat_history(session_id: str) -> StreamingResponse:
Yess! I'll update the function as soon as controller is finished!

2024-11-04 16:22 UTC, SoumyaRanjanPatnaik commented on backend/db/db_queries.py
> +        ai_response=ai_response,
Need to store the SQL results somewhere.

2024-11-07 05:56 UTC, SoumyaRanjanPatnaik commented on backend/fastapi-sse/server-sse.py
> +    print("type", chat_request.type)
Can you remove these files?

2024-11-07 09:29 UTC, Mirza-Aasim commented on backend/fastapi-sse/server-sse.py
> +    print("type", chat_request.type)
Done

2024-11-07 09:30 UTC, Mirza-Aasim commented on backend/server.py
> +async def stream_chat_history(session_id: str) -> StreamingResponse:
Resolved

2024-11-07 09:30 UTC, Mirza-Aasim commented on backend/fastapi-sse/logger.py
Deleted!

2024-11-07 09:31 UTC, Mirza-Aasim commented on backend/fastapi-sse/server-sse.py
Yes deleted!

2024-11-07 09:46 UTC, SoumyaRanjanPatnaik requested changes

2024-11-07 09:51 UTC, Mirza-Aasim commented on backend/server.py
> +    allow_origins=["*"],
Resolved!

2024-11-07 09:51 UTC, Mirza-Aasim commented on backend/controllers/sql_response.py
> +from google.generativeai.
Removed invalid import!

2024-11-07 09:52 UTC, merged